pipeline {
    agent { label "dev" }

    stages {
        stage("Code Clone") {
            steps {
                script {
                    git branch: 'main', url: 'https://github.com/mayurbagewadi/devops.git'
                }
            }
        }

        stage("Build") {
            steps {
                sh '''
                    cd two-tier-flask-app
                    docker build --no-cache -t two-tier-flask-app -f Dockerfile .

                '''
            }
        }

        stage("Test") {
            steps {
                echo "Developer / Tester tests likh ke dega..."
            }
        }

        stage("Push to Docker Hub") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        docker login -u $DOCKER_USER -p $DOCKER_PASS
                        docker tag two-tier-flask-app $DOCKER_USER/two-tier-flask-app:latest
                        docker push $DOCKER_USER/two-tier-flask-app:latest
                    '''
                }
            }
        }

        stage("Deploy") {
            steps {
                // Best practice: use dir() to run inside the folder
                dir('two-tier-flask-app') {
                    sh 'docker compose up -d --build --force-recreate flask-app'
                
                }
            }
        }
    }
}
